mozilla-services/shavar

- shavar/parse.py
- shavar/tests/base.py
- shavar/tests/test_parse.py
- shavar/tests/tests.ini
- shavar/types.py
Turns out that no limits on the number of chunks a client can report in a request in combination with using time_t as a chunks numbers makes for some hilariously bad behaviour. @rfk r?
> Fix for a potentially nasty resource consumption bug

- setup.py
- shavar/tests/test_views.py
- shavar/views/__init__.py
In this week's thrilling episode, our hero realizes he was an idiot several
times over but adroitly avoids disaster with some last minute hacking to
provide a saner fix for the ugly OOM causing feature that breaks clients!
This change actually makes use of the data parse from the client request to
provide an explicit list of chunks to delete.  Due to the internal data
structures that expand ranges after parsing, I decided to forego coalescing
those from their constiuent chunk numbers.  This just means that the client
will get a long-ish list of chunks to delete the first time they connect after
deployment.
> Better fix for non-delta publishing(issue #27)

- requirements.txt
- setup.py
Downgrading unittest2 to a previous version because one of its dependencies is
horked.  Bumping the release as a consequence.
> Quick fix for broken unittest2 dependencies

- setup.py
- shavar/parse.py
- shavar/tests/test_parse.py
- shavar/tests/test_views.py
- shavar/views/__init__.py
- Permit single prefix requests
- Return a 204(as spec'd) when no matching hash is found for a prefix
- More thorough tests for gethash error conditions
I am very surprised that these haven't been in production for months.  The
work was done then I didn't push.  I suspect it was due to the confusion about
which release was actually running in production at the time.
r? @rfk
> Fixes for gethash issues

- shavar/tests/test_views.py
- shavar/views/__init__.py
Fixes issue #38.  When not_publishing_deltas is enabled for a list, only
include an "ad:" line when there are actually chunks to be dropped from the
client.
> Properly send adddels with not_publishing_deltas

- setup.py
- shavar/lists.py
- shavar/tests/test_lists.py
- shavar/tests/tests.ini
This managed to get left out of PR #48 for reasons that are quite beyond me.
Properly check for the refresh_check_interval at the list level and at the
global level.
Change the hard coded, fallback default to 10 minutes.
Add a test to actually make sure the config setting works
r? @telliott
> Fix missing data freshness check

- setup.cfg
- shavar.testing.ini
- shavar/views/__init__.py
Add logging.LogFilter to both the mozsvc.metrics and wsgi loggers so they
will STFU with the 200s already.
r? @fmarier
> Additions to make it possible to silence HTTP 200 logging for prod

- shavar/parse.py
- shavar/tests/test_parse.py
- shavar/views/__init__.py
As reported by @palant:
Issue #64: Incorrect usage of str.split()
Issue #65: Uncaught exception if a request line doesn't contain a semicolon
Issue #66: Dead code: variable claims in shavar.parse.parse_downloads()
Issue #67: shavar.parse.parse_gethash() asks for denial-of-service
Plus some additional robustness for parse_gethash while we're about it.
r? @fmarier
> Four fixes for four wonderful issues!

- shavar/parse.py
- shavar/tests/test_parse.py
io.IOBytes doesn't have a peek() method.  Pyramid's DummyRequest body_file
apparently isn't instantiated as an IOBytes object.  Another victim to
significant departures in Pyramid's testing infrastructure from normal
production behaviour, sadly.
r? @fmarier
> Remove oversize gethash request check

- shavar/views/__init__.py
The goal of this patch is to prevent users from injecting content in the 404 page with `https://shavar.services.mozilla.com/==go%20to%20https://evildomain.com`.
Note: I've never coded with pyramid before, and I don't have the infrastructure to test this patch, but it _seems_ _sensible_...
> Handle 404s gracefully

- .dockerignore
- .gitignore
- Dockerfile
- circle.yml
- startup.sh
add an exec to the start up script
pass START arg to circle test
missing space; added
add a push for testing_.* branches
add code required to install the newrelic agent in the container if desired
add logic to start via the newrelic wrapper if -e ENABLE_NEWRELIC is set on the docker run command line
circleci's docker doesn't support the ARG spec. Lame.
ignore newrelic.ini if it exists
require newrelic
unstage change to requirements.txt
Dockerfile changes
- set a sane default for NEWRELIC_LIC_KEY
- Don't generate newrelic.ini on container build, generate at runtime in
response to ENV vars set on command line instead
startup.sh changes
if ENABLE_NEWRELIC is set and the config file doesn't exist. Generate
one and set the appropriate app name. The newrelic-admin script is brain
dead and …
> Start up script changes and optional new relic support

- shavar/templates/swagger.mako
This flag let us know that all the APIs are described in the swagger spec
> added the fullEndpointsDescription flag

- requirements.txt
- shavar/lists.py
- shavar/parse.py
- shavar/sources.py
- shavar/tests/test_lists.py
- shavar/views/__init__.py
Now that versioned lists are available in https://github.com/mozilla-services/shavar-list-creation/pull/92 this PR allows Firefox client to receive the versioned lists to enable testing of changes in the disconnect list as mentioned in https://github.com/mozilla-services/shavar-list-creation/issues/90.
1. Add AWS credentials
```
export AWS_ACCESS_KEY_ID=<access_key>
export AWS_SECRET_ACCESS_KEY=<secret_key>
```
2. Include the `.ini` files of the lists you want to check for updates and download by adding them into `<project root>/shavar/tests/list_served`. For sample `.ini` file refer to [shavar-server-list-configs](https://github.com/mozilla-services/shavar-server-list-config)
3. Change the`source` and `redirect_url_base` in`.ini` to point to the S3 instance and cloudfront you want to use …
> Signed get versions lists from S3

- shavar/lists.py
- shavar/tests/test_lists.py
- shavar/views/__init__.py
After pushing https://github.com/mozilla-services/shavar/pull/111 and testing we found the issue https://github.com/mozilla-services/shavar-list-creation/issues/106. This PR changes the `get_list` and `match_with_versioned_list` to return version number to return the path to versioned chunknum. Previously this code was first seen here https://github.com/mozilla-services/shavar/pull/111 under commits:
- 11b9dff
- 2af89a5
- acaefc3 
1. Add AWS credentials
```
export AWS_ACCESS_KEY_ID=<access_key>
export AWS_SECRET_ACCESS_KEY=<secret_key>
```
2. Include the `.ini` files of the lists you want to check for updates and download by adding them into `<project root>/shavar/tests/list_served`. For sample `.ini` file refer to [shavar-server-list-configs](https://github.com/mozilla-services/shavar-ser …
> Return versioned chunk num path

- shavar/lists.py
- shavar/tests/test_lists.py
The lazy match, which truncates the `app_ver` value sent via query param in the downloads request, does not check for the major version trailing with `.0`. https://github.com/mozilla-services/shavar/pull/120/commits/44df7b981a3f5ae8293508223ca5890d1b8f2675 in this PR fixes that.
Additionally, while testing for `NoAuthHandler` error mentioned in https://github.com/mozilla-services/shavar/pull/119 on Staging by making thousands of requests, we noted that `MissingListDataError` that was happening on [Production](https://sentry.prod.mozaws.net/operations/shavar-prod/issues/6665885/?query=is:unresolved) happening in [Staging](https://sentry.prod.mozaws.net/operations/shavar-stage/issues/6651487/?query=is:unresolved) without triggering the `NoAuthHandler` error on Staging. …
> Fix MissingListDataError and return matched major version

- .boto
- shavar/lists.py
After pushing changes on https://github.com/mozilla-services/shavar/pull/115 to production we rolled back due to latency not dropping as mentioned in [bugzilla here](https://bugzilla.mozilla.org/show_bug.cgi?id=1597531). We added additional hosts in 22:35 but latency returned as seen in the image below
along with `NoAuthHandlerFound` error from boto and `MissingListDataError` popping up in Sentry. While attempting to replicate on local environment, when a thread gets the `NoAuthHandlerFound` error from boto the thread becomes unusable (returns 5xx) and hangs which could explain the increase of 5xx and latency when https://github.com/mozilla-services/shavar/pull/115 was deployed.
To fix this issue I referred to [this bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1006954) …
> Add boto config for retrying

- shavar/lists.py
[Including all the regional Google domains](ttps://github.com/mozilla-services/shavar-prod-lists/pull/78) broke Shavar because it increased the entity list from ~300KB to 1.5MB. When creating the `mozstd-trackwhite-digest256`, remove the Google properties and resources and create a separate entity list google-trackwhite-digest256.
##
Dependent on https://github.com/mozilla-services/shavar-server-list-config/pull/29
Dependent on successful test on Staging and https://github.com/mozilla-services/shavar-server-list-config/pull/29 for Prod environment configuration
> Get versioned entity lists

- shavar/lists.py
While testing for #122 on Staging `'NoneType' object has no attribute 'etag'` events occurred for the first time ([logged in Sentry](https://sentry.prod.mozaws.net/operations/shavar-stage/issues/6895806/?query=is:unresolved)). Even after fixing the malformed versioned list path in #124, the event continued to occur. The error was reproducible if the versioned list was not found in the S3 but was under the served list by Shavar. This PR blocks versioned lists not found in the S3 to be listed as served in Shavar.
1. In your local S3 bucket for Shavar, remove a versioned list (e.g. delete the list in `tracking/72.0/base-fingerprinting-track-digest256` to delete the 72.0 versioned list for `base-fingerprinting-track-digest256`)
2. Run the command: `curl -d " " …
> Remove support for not found list

- shavar/lists.py
- shavar/tests/lists_served/test-track-digest256.ini
- shavar/tests/lists_served_s3/test-track-digest256.ini
- shavar/tests/test_lists.py
- shavar/tests/test_views.py
Fix #144
```
shavar.exceptions.NoDataError: No chunk file found at "s3+file://net-mozaws-prod-shavar/entity/74.0/73.0/72.0/71.0/70.0/69.0/google-trackwhite-digest256"
```
It should look like
```
shavar.exceptions.NoDataError: No chunk file found at "s3+file://net-mozaws-prod-shavar/entity/69.0/google-trackwhite-digest256"
```
Check that the same error message mentioned in A/C is shown when the versioned list does not exists
1. Comment out the [lines added](https://github.com/mozilla-services/shavar/pull/145/files#diff-f69e5e9f0be67b9ee6425c17d3bf1005R71-R73) in shavar/lists.py
2. Run tests for `AddVersionedListsTest` by running: `nosetests -s --nologcapture ./shavar/tests/test_lists.py:AddVersionedListsTest`
3. Check that the log looks like:
```
No index file found at …
```
> Revert the versioned source for lists to the original

- mozsvc/util.py
Sentry expects record.message field but our custom formatter, `JsonLogFormatter`, does not fill the record's message resulting in "Top level Sentry exception" logged in startup and refresh of Shavar. Fixes #146
1. Ping me for `shavar.ini` setup
2. Get Sentry account setup
3. Start Shavar and check that the following error is raised from `NoDataError` raised in `load()` call in `shavar/sources.py`
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/raven/handlers/logging.py", line 97, in emit
return self._emit(record)
File "/usr/local/lib/python3.7/site-packages/raven/handlers/logging.py", line 161, in _emit
handler_kwargs[\'formatted\'] = text_type(record.message)
AttributeError: \'LogRecord\' object has no attribute \'message\''
```
1. Follow the previous …
> Fill in the record.message

- shavar.ini
Reduce debug outputs with 2xx responses by using uWSGI flags.
1. Run Shavar
2. Make a POST request to `/list` endpoint and check that the 200 log shows up
3. Make a POST request to `/lists` endpoint and check that the 404 log shows up
1. Go to `shavar.ini` and under the section for `shavar` add the `stfu_200_logging = True`
2. Run Shavar
3. Make a POST request to `/list` endpoint and check that the 200 log DOES NOT show up
4. Make a POST request to `/lists` endpoint and check that the 404 log DOES show up
@ckolos if you want to filter out the 2xx log messages you need to add the following code snippets into the `[uswgi]` section in the `.ini`
```
disable-logging = True
log-4xx = True
log-5xx = True
```
After doing so, if you set the `stfu_200_logging` into `True` 2xx logs should no longer …
> Reduce debug outputs

- shavar/__init__.py
- shavar/views/__init__.py
After #149, we expected the update to `sentry_sdk` will fix #150. However, the events did not get grouped properly as the messages were unique and no stack trace were passed (no stack trace passed because the exception was not thrown and instead we caught logged the error). The changes here uses `before_send` to group the events using the `fingerprint` attribute of the sentry event.
1. Execute the following command:
`curl -d "mozstd-trackwhite-digest256;a:9-3;" "localhost:8080/downloads?appver=76.0&pver=2.2"ps`
2. Check that an issue with error message `Invalid RANGE "9-3;" for mozstd-trackwhite-digest256` is logged on Sentry
3. Execute the following command:
`curl -d "mozstd-trackwhite-digest256;a:1234567890-3;" "localhost:8080/downloads?appver=76.0&pver=2.2"`
4. Check that issue is also …
> Group invalid range events using Sentry fingerprint

- shavar/lists.py
`configparser.NoSectionError: No section: 'base-email-track-digest256'` was fixed by:
- adding the configurations for email trackers to be served by Shavar [here](https://github.com/mozilla-services/shavar-server-list-config/pull/33)
- skipping versioning for email tracker list if the version is older (lower) than `97` since the email categories were introduced in `97` and later (higher) versions.
This PR also fixes the previous issue with the GitHub API **not** returning the entire versioned list due to pagination in the request (same problem experienced and fixed in shavar-list-creation [here](https://github.com/mozilla-services/shavar-list-creation/pull/179)).
#
Changes are safe to go to Stage and Prod since
```python
list_name in EMAIL_TRACKER_LISTS
```
in shavar/lists.py will ALWAYS …
> Serve email trackers

- shavar/lists.py
The latest `Stage` keeps returning that the `branch` is a string when we are expecting a dictionary. This PR catches, handles, and logs the exception so that `Stage` can build successfully.
> Log and skip branch str when expecting dict

- shavar/lists.py
Removing duplicate code that skips if the email tracker versioned list does NOT exist which was already handled later in the code:
https://github.com/mozilla-services/shavar/blob/1faa18996a1b4082e446ed922744186c16435286/shavar/lists.py#L86-L97
> Remove duplicated skip logic

- .circleci/config.yml
- README.md
- shavar.ini
- shavar/__init__.py
To move from Sentry to Sentry IO, we need to add some new configurations `sentry_dsn` and `sentry_env`.
[Configurations doc](https://docs.sentry.io/platforms/python/configuration/options/#dsn). Variable used by the Sentry SDK that tells where to send the events.
[Configurations doc](https://docs.sentry.io/platforms/python/configuration/options/#environment). Variable used by Sentry IO to associate release/environment for cleaner Sentry project management.
> Add Sentry IO configurations
